### ISSUE TITLE
Failed run ci in action github

### ISSUE THREAD

**Issue by brunoalvesdasilva** [reviewdog/action-stylelint#116]
Hello everyone, I have a question.

We are receiving this error in our company's action, and apparently we have not made any changes.

Is there anything we can do to solve it? We temporarily fixed the version at 1.18.1 and it is correct, but in the last version it does not work, always generating this error.

![image](https://github.com/reviewdog/action-stylelint/assets/1881558/23174c1c-3c79-4703-8a1d-a8883cffd18e)

in action code:

```yml
    - name: Run reviewdog stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ****
          reporter: github-pr-check
          filter_mode: nofilter
          stylelint_input: src/**
          fail_on_error: true
```
