### ISSUE TITLE
multiple lint runners

### ISSUE THREAD

**Issue by tadjohnston** [reviewdog/action-stylelint#13]
I'd love to be able to do something like the following as we are transitioning to TailwindCss. 

``` yml
name: stylelint
on: [pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'stylelint tailwind'
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          stylelint_input: 'src/**/*.tw.{css,scss}'
  stylelint-themed:
    needs: stylelint
    name: runner / stylelint / themed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'stylelint react-themed'
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          stylelint_input: 'src/**/_home.{css,scss}'
```

Unfortunately when I add a file in each input that I know will fail, I do not get all failures. Instead, whatever runner runs last trumps the first and only reports the errors from the one runner and not both. When I only run one of these at a time, it does what it's supposed to.

Example:

These are errors from `stylelint tailwind`
![Screen Shot 2020-05-07 at 10 01 30 AM](https://user-images.githubusercontent.com/10748767/81323124-c2986100-9049-11ea-934c-77a8b9e194f1.png)

I also get the errors I should for `stylelint react-themed`, but they never show up in the report. Here is the file that I've forced to have errors:

![Screen Shot 2020-05-07 at 10 03 01 AM](https://user-images.githubusercontent.com/10748767/81323364-1efb8080-904a-11ea-808c-d4e7797d5351.png)

Is this something that can be adjusted with action-stylelint here or is this a restriction of reviewdog itself?
