### ISSUE TITLE
Unable to lint only specific files

### ISSUE THREAD

**Issue by mihkelviilveer** [reviewdog/action-stylelint#23]
Currently it is possible to lint only one file or glob match. Is it possible to add support for custom list of files to be linted? It should be only matter of removing quotes from stylelint first argument.

Input which does lint successfully:

```
with:
    github_token: ***
    stylelint_input: src/scss/bootstrap-ext/_input-group.scss src/scss/bootstrap-ext/_tables.scss
    stylelint_config: .stylelintrc.json
    level: warning
    reporter: github-check
    name: stylelint
    workdir: .
```

Using input like this works:

```
with:
    github_token: ***
    stylelint_input: src/scss/bootstrap-ext/_input-group.scss
    stylelint_config: .stylelintrc.json
    level: warning
    reporter: github-check
    name: stylelint
    workdir: .
```
