### ISSUE TITLE
Question | How to specify number of changed lines in diff_context 

### ISSUE THREAD

**Issue by a-kosanovic** [reviewdog/action-stylelint#43]
Hi, I've searched the whole documentation but can't figure how to specify the no of lines for the `diff_context`, or is this even possible: `changed lines +-N lines (N=3 for example).` https://github.com/reviewdog/reviewdog#diff_context 

This is not working for me: 
```
 - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          filter_mode: diff_context(5)
          reporter: github-pr-review 
          workdir: "./app/"
          stylelint_input: "**/*.scss"

```
