### ISSUE TITLE
Stylelint not found

### ISSUE THREAD

**Issue by wrux** [reviewdog/action-stylelint#5]
I have setup a workflow using the example. When the workflow executes I get this message:

```
/entrypoint.sh: line 11: /github/workspace/node_modules/.bin/stylelint: not found
/entrypoint.sh: line 15: /github/workspace/node_modules/.bin/stylelint: not found
```

I have tried adding an `npm install` command into the step to install dependencies but when it runs, stylelint is not found. Have I missed something here? 

Here's my workflow file:
```
name: reviewdog

on: [pull_request]

jobs:

  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - name: depencies
        run: npm install -g stylelint stylelint-scss stylelint-order stylelint-selector-bem-pattern
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_input: 'web/app/Components/**/*.scss'
```
