### ISSUE TITLE
Ancient lockfile -> ENOENT -> stylelint not found

### ISSUE THREAD

**Issue by pbrisbin** [reviewdog/action-stylelint#75]
Trying to get setup with a basic configuration and the Action fails with:

![](https://files.pbrisbin.com/screenshots/screenshot.728083.png)

Is this an issue on my end?

Our config:

```yaml
name: Stylelint

on:
  pull_request:

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-stylelint@v1
        with:
          level: warning
          fail_on_error: true
          stylelint_input: "**/*.scss"
          stylelint_config: frontend/.stylelintrc
```
