### ISSUE TITLE
reviewdog: PullRequest needs 'git' command: failed to run 'git rev-parse --show-prefix': exit status 128

### ISSUE THREAD

**Issue by bailing-li-miidas** [reviewdog/action-stylelint#78]
Until yesterday It runs successfully, but getting the above error when trying to run reviewdog in github actions.
 
```
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/checkout@v2
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-hoge-ci-reviewdog-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-hoge-ci-reviewdog-
      - name: Install depencies
        run: |
          npm install
      - name: Stylelint review
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review
          stylelint_input: './**/*.scss'
          filter_mode: file
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
```
